# Generated by Django 4.2.9 on 2024-11-16 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_bill_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 19, 59, 20, 144757, tzinfo=datetime.timezone.utc)),
        ),
    ]
