# Generated by Django 4.2.16 on 2024-11-17 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_bill_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 17, 9, 1, 19, 6266, tzinfo=datetime.timezone.utc)),
        ),
    ]
