# Generated by Django 4.2.16 on 2024-11-17 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_bill_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 17, 9, 27, 16, 552273, tzinfo=datetime.timezone.utc)),
        ),
    ]
