# Generated by Django 5.0.9 on 2024-11-17 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_bill_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 17, 9, 56, 50, 125515, tzinfo=datetime.timezone.utc)),
        ),
    ]
