# Generated by Django 4.2.9 on 2024-11-16 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 19, 52, 50, 165110, tzinfo=datetime.timezone.utc)),
        ),
    ]
