# Generated by Django 4.2.9 on 2024-11-16 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 19, 59, 20, 156262, tzinfo=datetime.timezone.utc)),
        ),
    ]
