# Generated by Django 4.2.16 on 2024-11-17 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 17, 9, 1, 19, 10276, tzinfo=datetime.timezone.utc)),
        ),
    ]
