# Generated by Django 4.2.16 on 2024-11-17 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventory_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 17, 9, 41, 49, 511461, tzinfo=datetime.timezone.utc)),
        ),
    ]
