# Generated by Django 5.0.9 on 2024-11-17 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 17, 9, 56, 50, 148346, tzinfo=datetime.timezone.utc)),
        ),
    ]
